import mongoose, { Document, Schema } from 'mongoose';
 
export interface IMember extends Document {
  username: string;
  password: string; // Hash this in production!
  createdAt: Date;  // Auto-generated by Mongoose when timestamps: true
  updatedAt: Date;  // Auto-generated by Mongoose when timestamps: true
}
 
const MemberSchema: Schema<IMember> = new Schema(
  {
    username: {
      type: String,
      required: true,
      unique: true,
    },
    password: {
      type: String,
      required: true,
    },
  },
  {
    timestamps: true, // Automatically adds createdAt and updatedAt
  }
);
 
// ✅ Explicitly set collection name to 'admins'
export const Member =
  mongoose.models.Member ||
  mongoose.model<IMember>('Member', MemberSchema, 'admins');
  